server:
  port: 8080
  context-path: /
  tomcat:
    max-threads: 800
    accept-count: 2000
    min-spare-threads: 10
  compression:
    enabled: true
    mime-types:
    - text/html
    - text/plain
    - text/css
    - text/xml
    - application/xml
    - application/json
spring:
  profiles:
    active: local
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: spring-cloud-tonfay-submit-test
  redis:
      host: redis.shouqiev.net
      port: 6379
      password: 3QpT%LA5
      pool.max-active: 8
      pool.max-idle: 8
      pool.max-wait: -1
      pool.min-idle: 0
      timeout: 0
